# Build plugin with Maven
# https://www.spigotmc.org/threads/github-actions-build-jar-with-maven.425246/#post-3738223
name: Java (Spigot Plugin) CI with Maven

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the rewrite branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # https://github.com/actions/setup-java
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 17
          # Java distribution. See the list of supported distributions in README file
          distribution: temurin
          # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven#caching-dependencies
          cache: maven
      
      # https://github.com/SpraxDev/Action-SpigotMC
      - uses: SpraxDev/Action-SpigotMC@v4
        with:
          # A comma-separated list of Spigot version that should be compiled
          # These values are later given to the BuildTools.jar as '--rev' argument
          #
          # Example: latest, 1.14.4, 1.8.8
          versions: 1.18.2 # Optional
          
          # Should sources be generated?
          # If enabled, BuildTools is provided the '--generate-source' argument
          generateSrc: false # Optional

          # Should the documentation be generated?
          # If enabled, BuildTools is provided the '--generate-docs' argument
          generateDoc: false # Optional

          # Should we disable the BuildTools's Java-Version-Check?
          # If enabled, BuildTools is provided the '--disable-java-check' argument
          disableJavaCheck: false # Optional

          # Should we use the SpecialSource-Plugin to deobfuscate Mojang-NMS?
          # If enabled, BuildTools will install the SpecialSource-Plugin and 'remapped'-Version of Spigot without obfuscation
          remapped: false # Optional

          # Disables the check for existing files in the local maven repository
          # Normally, a version is skipped if it is already installed
          # in the local maven repository to speed up build time
          forceRun: false # Optional

          # The amount of builds allowed to run at the same time
          # Set to '-1' to use system's cpu core count
          threads: -1 # Optional

          # You can choose between different BuildTools to be used by this action
          # Available: SpigotMC
          buildToolProvider: SpigotMC # Optional

      # Build and package the plugin with Maven
      - name: Build with Maven
        run: mvn -X clean package --file pom.xml
      # https://stackoverflow.com/q/65743472
      # https://github.com/marketplace/actions/upload-a-build-artifact
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: artifact
          path: |
            target/*.jar
            !target/original-*.jar
            !target/*-shaded.jar
